development:
  facebook:
    key: <%= ENV['facebook_key'] %>
    secret: <%= ENV['facebook_secret'] %>
  twitter:
    key: <%= ENV['twitter_key'] %>
    secret: <%= ENV['twitter_secret'] %>
test:
  facebook:
    key: <%= ENV['facebook_key'] %>
    secret: <%= ENV['facebook_secret'] %>
  twitter:
    key: <%= ENV['twitter_key'] %>
    secret: <%= ENV['twitter_secret'] %>

production:
  facebook:
    key: <%= ENV['FACEBOOK_KEY'] %>
    secret: <%= ENV['FACEBOOK_SEECRET'] %>
  twitter:
    key: <%= ENV['TWITTER_KEY']%>
    secret: <%= ENV['TWITTER_SEECRET'] %>
